version: '2'

networks:
  Cloud_Computing_Projekt_Network:
    driver: bridge


services:
  srv_webserver:
    image: ccp/srv_webserver
    hostname: srv_webserver
    container_name: srv_webserver
    restart: unless-stopped
    ports:
      - 80:${SERVER_PORT}
    build:
        context: ./
        dockerfile: Dockerfile